### ISSUE TITLE
我准备试试 但我cpu是10200h

### ISSUE THREAD

**Issue by n-WN** [192421532/Dell-G3-3500#1]
我曾经尝试过在我的台式机上黑，了解到CPU小差别应该影响不大，可惜我硬盘是海力士 bc711

看起来得换一个了

**Comment by n-WN** [comment]
# 已经下单了大华c900 plus 等到货 也clone了项目和下了bigsur 11.7 dmg镜像 先在机械装一下

**Comment by Passenger-bee** [comment]
> 

好的 期待你的成功！

**Comment by n-WN** [comment]
> > 
> 
> 好的 期待你的成功！

有联系方式吗麻烦咨询一下 我下载了11.7，黑果小兵的 跑码后就进bios ，替换了你的efi 能看到苹果图标，但是卡进度条（这台电脑第一次安装

**Comment by n-WN** [comment]
我把海力士固态拔了就能进了 草 哈哈哈

**Comment by n-WN** [comment]
怪起来了 进入开机引导就屏幕显示怪异
![MVIMG_20230512_213941.jpg](https://github.com/Passenger-bee/Dell-G3-3500/assets/30841158/eeaf0ccc-4687-4439-9734-38cd11eecd70)

**Comment by n-WN** [comment]
> 怪起来了 进入开机引导就屏幕显示怪异
> ![MVIMG_20230512_213941.jpg](https://github.com/Passenger-bee/Dell-G3-3500/assets/30841158/eeaf0ccc-4687-4439-9734-38cd11eecd70)
> 
> 

跟我用机械硬盘有关系？我三年前在机械上面安装没问题啊 （只是慢

**Comment by n-WN** [comment]
我准备改dvmt 但是bios没法提取，大佬说10200h核显是610换皮，十代只有10200h不能确定 麻了

**Comment by n-WN** [comment]
我准备改dvmt 但是bios没法提取，大佬说10200h核显是610换皮，十代只有10200h不能确定 麻了
![IMG_20230513_153755.jpg](https://github.com/Passenger-bee/Dell-G3-3500/assets/30841158/b11ad24d-f47f-4658-92b0-184e51cc44d3)

改了dvmt和cfg lock 还是花屏，放弃了 就我这款处理器不行，麻麻地

**Comment by Passenger-bee** [comment]
昨天在忙，加我微信LL192421532 详聊

**Comment by Passenger-bee** [comment]
> ，

我又改了一下，之前那个版本传错了，用0.6.3试试

**Comment by n-WN** [comment]
> 昨天在忙，加我微信LL192421532 详聊

好的 谢谢

**Comment by n-WN** [comment]
> > ，
> 
> 我又改了一下，之前那个版本传错了，用0.6.3试试

不过感觉也于事无补 这款cpu 核显无法驱动

**Comment by n-WN** [comment]
![image](https://github.com/Passenger-bee/Dell-G3-3500-BigSur/assets/30841158/3bad0398-680d-427b-8588-4ca3b04054b2)

**Comment by n-WN** [comment]
![image](https://github.com/Passenger-bee/Dell-G3-3500-BigSur/assets/30841158/f70723e5-5e2f-4101-a7ed-cc4db83d0444)
