### ISSUE TITLE
bigsur的问题

### ISSUE THREAD

**Issue by 3037456978** [192421532/Dell-G3-3500#2]
bigsur11.7正式版
我已经更换过博通网卡，但是还是无法使用Wi-Fi蓝牙以及隔空投送！！！

**Comment by Passenger-bee** [comment]
您好！请问你的无线网卡是什么型号的吗？是免驱的吗？加入BrcmPatch.kext（博通网卡驱动）试一试

**Comment by 3037456978** [comment]
你有QQ或者微信吗？我感觉一句话说不清楚😭

**Comment by 3037456978** [comment]
![Uploading IMG_2285.png…]()

**Comment by Passenger-bee** [comment]
这样 你加我WeChat吧
![IMG_2660](https://github.com/Passenger-bee/Dell-G3-3500-BigSur/assets/76861573/71169917-5a14-478a-af9a-251d5641402b)

**Comment by Passenger-bee** [comment]
这样  你加我WeChat吧
![IMG_2660](https://github.com/Passenger-bee/Dell-G3-3500-BigSur/assets/76861573/b7889caa-0153-477c-926e-8c3d31869851)
